### ISSUE TITLE
Randr binding broken

### ISSUE THREAD

**Issue by Dou2ble** [SolitudeSF/xcb#1]
Just a simple hello world with the randr binding dosent compile

Trying to compile:
import xcb/randr
echo "Hello World"

output:
/home/user/.nimble/pkgs/xcb-0.2.0/xcb/render.nim(45, 5) Error: expected: ':', but got: '{.'

The randr bindings worked fine in version 1.1.0 of your bindings. pls fix

**Comment by SolitudeSF** [comment]
this should do it https://github.com/SolitudeSF/xcb/commit/33773c24ca0c07fb2a4bc9af6608d47510821844
